### ISSUE TITLE
Add seqkit to coidb dependencies; issue in clustering

### ISSUE THREAD

**Issue by tjcreedy** [biodiversitydata-se/coidb#18] opened 2022-06-22 07:19 UTC
Hi, a couple of snags I hit. I'm running on a cluster using slurm job manager, so the run occurs in a near-default system environment, running with a conda environment containing only coidb.

Initially, `remove_non_standard` fails because seqkit is not installed. An easy fix to install seqkit into the environment, just a note that it's a dependency missing from the coidb conda install.

I then hit a more confusing issue, that `cluster` hangs for a long period, in this case for about 12 hours, before crashing. The end of the STDERR log looks like this:

```
[Tue Jun 21 12:48:50 2022]
rule cluster:
    input: bold_filtered.fasta
    output: bold_clustered.fasta
    log: logs/bold/cluster.log
    jobid: 3
    reason: Missing output files: bold_clustered.fasta; Input files updated by another job: bold_filtered.fasta
    threads: 10
    resources: tmpdir=/tmp, runtime=600

WorkflowError:
Failed to open source file <home>/miniconda3/envs/coidb/lib/python3.10/site-packages/coidb/envs/cluster.yml
FileNotFoundError: [Errno 2] No such file or directory: '<home>/miniconda3/envs/coidb/lib/python3.10/site-packages/coidb/envs/cluster.yml'
Removing output files of failed job cluster since they might be corrupted:
bold_clustered.fasta
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-21T120759.823981.snakemake.log
/var/spool/slurm/slurmd/job85596/slurm_script: line 13: 674824 Bus error               (core dumped) coidb -j 20
```
As you can see, it started this rule about 40 minutes after starting the run. The run failed at 00:17 this morning.
The `logs/bold/cluster.log` file looks like this:
```
Reading bold_filtered.fasta and clustering with vsearch...
Records read: 6540815
BOLD IDs clustered: 517543
Sequence clusters: 678981
```
Let me know if you need any more info!

**Comment by johnne** [comment] 2022-08-20 06:56
Hi @tjcreedy and thanks for submitting this issue!

I've updated the bioconda recipe so that `seqkit` is now a required dependency which should take care of the first problem.

The second issue is strange because to me it looks like clustering completed but the workflow complained about a missing file (`envs/cluster.yml`). This is an old reference that I've forgot to delete. The line of code has now been removed from the package and hopefully the issue is fixed in the new version of `coidb`. I'm updating the bioconda recipe now but if you don't want to wait for the next version to be uploaded to anaconda you can download the latest release from the Releases page and install directly from there.

Let me know how it goes!

**Comment by tjcreedy** [comment] 2022-08-24 08:36
Hi, I've run again and it works! I get all the bold_* files I expected. Thank you.

One minor point - I note you've updated the README.md, but I found the original version with the instructions very handy - has this moved somewhere else?

**Comment by johnne** [comment] 2022-09-28 05:49
@tjcreedy The original instructions have now been placed in the repo Wiki.

**Closed by johnne** 2022-09-28 05:49 UTC
